### ISSUE TITLE
jinja2.exceptions.TemplateRuntimeError

### ISSUE THREAD

**Issue by GuoMingXiang-code** [biowdl/wdl-aid#18]
Hello, Thank you for your tools. When I use it, the “jinja2.exceptions.TemplateRuntimeError: No filter named 'items' found.” error pops up. I want to ask why.

**Comment by DavyCats** [comment]
What version of jinja do you have installed? I just checked in the jinja changelog and it seems the `items` filter was added in version 3.1.0.
